
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.6.0
    hooks:
    -   id: mdformat

-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
